### ISSUE TITLE
Passing in value and handleChange

### ISSUE THREAD

**Issue by mrn3** [samrandhawa4/mui-autocomplete#1]
So mui-autocomplete is just what I need (especially with the outlined variant), but I don't see how I can pass in value and handleChange function without messing it up.  I would like it to be on a form where I populate it with values the user has already input.  Please give me some guidance or an example.  

Also, do you have an example where it can accept values that are not in the list?

**Comment by samrandhawa4** [comment]
Sorry @mrn3 for late reply, i can help you in implementing this pacakage in your form if you will share your code or just give me a time so i can update onchange event with existing values for this pacakage.

**Comment by mrn3** [comment]
Okay, I actually moved onto another option, but I would be interested to see what you do as a solution

**Comment by samrandhawa4** [comment]
> Okay, I actually moved onto another option, but I would be interested to see what you do as a solution

Hi , our new mui-autocomplete is launched with avatar view and for static calls. Please visit our website for more info. Now callback functioning is also avaible.

**Comment by mrn3** [comment]
okay great - thx for the follow up
